"""Keyword rules for independent multi-label news detection.

The rules intentionally contain only the nine labels allowed by the product
contract. Broad labels such as "Gündem", "Diğer", "Genel" and "Bilinmeyen"
are never emitted by this module.
"""

from __future__ import annotations

from .models import ALLOWED_LABELS

LABEL_KEYWORDS: dict[str, dict[str, float]] = {
    "Teknoloji": {
        "teknoloji": 1.8,
        "yapay zeka": 2.6,
        "ai": 1.4,
        "openai": 2.5,
        "chatgpt": 2.3,
        "gemini": 1.7,
        "claude": 1.5,
        "robot": 1.5,
        "yazılım": 1.9,
        "siber": 1.9,
        "girişim": 1.4,
        "startup": 1.7,
        "uygulama": 1.2,
        "telefon": 1.2,
        "nvidia": 2.0,
        "çip": 1.7,
        "semiconductor": 1.7,
        "artificial intelligence": 2.6,
        "software": 1.9,
        "cybersecurity": 2.0,
        "technology": 1.9,
        "apple": 1.1,
        "google": 1.1,
        "api": 1.2,
    },
    "Siyaset": {
        "siyaset": 1.8,
        "seçim": 2.1,
        "parti": 1.5,
        "meclis": 1.9,
        "tbmm": 2.2,
        "cumhurbaşkanı": 2.0,
        "bakan": 1.5,
        "milletvekili": 1.8,
        "chp": 2.0,
        "ak parti": 2.0,
        "mhp": 1.8,
        "iyi parti": 1.8,
        "yasa teklifi": 2.2,
        "anayasa": 1.9,
        "kabine": 1.6,
        "politics": 1.9,
        "election": 2.1,
        "parliament": 2.0,
        "president": 1.5,
        "government bill": 2.0,
        "senate": 1.6,
        "congress": 1.7,
    },
    "Spor": {
        "spor": 1.6,
        "futbol": 2.2,
        "basketbol": 2.1,
        "voleybol": 2.1,
        "süper lig": 2.3,
        "maç": 1.9,
        "gol": 1.7,
        "transfer": 1.7,
        "galatasaray": 2.1,
        "fenerbahçe": 2.1,
        "beşiktaş": 2.1,
        "trabzonspor": 2.0,
        "uefa": 1.9,
        "nba": 1.9,
        "champions league": 2.1,
        "football": 2.1,
        "basketball": 2.1,
        "match": 1.7,
        "goal": 1.6,
    },
    "Ekonomi": {
        "ekonomi": 1.8,
        "dolar": 2.0,
        "euro": 1.8,
        "altın": 1.8,
        "borsa": 2.0,
        "bist": 2.2,
        "enflasyon": 2.2,
        "faiz": 1.9,
        "merkez bankası": 2.3,
        "piyasa": 1.5,
        "kredi": 1.4,
        "vergi": 1.5,
        "zam": 1.2,
        "maaş": 1.3,
        "petrol": 1.3,
        "kripto": 1.7,
        "finans": 1.8,
        "yatırım": 1.6,
        "market": 1.4,
        "stocks": 2.0,
        "inflation": 2.2,
        "central bank": 2.3,
        "economy": 1.9,
        "rate cut": 1.8,
        "interest rate": 1.9,
        "investment": 1.5,
    },
    "Eğlence": {
        "eğlence": 1.8,
        "magazin": 2.0,
        "ünlü": 1.7,
        "dizi": 1.8,
        "yarışma": 1.5,
        "televizyon": 1.5,
        "oyun": 1.4,
        "game": 1.4,
        "celebrity": 2.0,
        "entertainment": 1.9,
        "series": 1.6,
        "streaming": 1.5,
        "netflix": 1.6,
    },
    "Sağlık": {
        "sağlık": 2.0,
        "hastane": 1.8,
        "doktor": 1.7,
        "hasta": 1.5,
        "ilaç": 1.7,
        "tedavi": 1.9,
        "ameliyat": 1.8,
        "aşı": 1.9,
        "virüs": 1.7,
        "kanser": 2.1,
        "health": 2.0,
        "hospital": 1.8,
        "doctor": 1.7,
        "vaccine": 1.9,
        "treatment": 1.9,
        "medicine": 1.6,
        "cancer": 2.1,
    },
    "Bilim": {
        "bilim": 2.0,
        "bilim insanları": 1.9,
        "araştırma": 1.8,
        "uzay": 2.1,
        "nasa": 2.3,
        "iklim": 1.9,
        "keşif": 1.7,
        "fosil": 1.8,
        "deney": 1.6,
        "teleskop": 1.8,
        "deprem araştırması": 1.8,
        "science": 2.0,
        "research": 1.8,
        "space": 2.1,
        "climate": 1.9,
        "discovery": 1.7,
        "scientists": 1.7,
        "experiment": 1.6,
    },
    "Dünya": {
        "dünya": 1.4,
        "abd": 1.6,
        "avrupa": 1.4,
        "rusya": 1.6,
        "ukrayna": 1.7,
        "iran": 1.5,
        "israil": 1.6,
        "gazze": 1.9,
        "filistin": 1.9,
        "çin": 1.5,
        "almanya": 1.3,
        "fransa": 1.3,
        "nato": 1.7,
        "bm": 1.7,
        "birleşmiş milletler": 1.8,
        "united nations": 1.8,
        "world": 1.6,
        "global": 1.3,
        "war": 1.6,
        "foreign": 1.5,
        "international": 1.7,
        "europe": 1.3,
        "russia": 1.5,
        "china": 1.4,
    },
    "Yaşam": {
        "yaşam": 1.7,
        "aile": 1.4,
        "eğitim": 1.6,
        "okul": 1.4,
        "öğrenci": 1.4,
        "seyahat": 1.6,
        "turizm": 1.6,
        "moda": 1.5,
        "yemek": 1.6,
        "tarif": 1.6,
        "ev": 1.2,
        "life": 1.7,
        "travel": 1.6,
        "education": 1.6,
        "school": 1.4,
        "lifestyle": 1.8,
        "food": 1.4,
        "recipe": 1.6,
    },
}

# Defensive import-time validation prevents accidental addition of unsupported labels.
_invalid_labels = set(LABEL_KEYWORDS).difference(ALLOWED_LABELS)
if _invalid_labels:
    raise ValueError(f"Unsupported multi-label rule keys: {sorted(_invalid_labels)}")
