import { fetchRoles, fetchUsers, updateUserRole, fetchAuditLogs } from '../utils/adminReportApi.js';
import { escapeHtml } from '../utils/textUtils.js';
export function initRoleManagementPage(rootId = 'role-management-root') {
  const root = document.getElementById(rootId); if (!root) return null;
  const state = { roles: [], users: [], logs: [], loading: false, message: '' };
  async function load() { state.loading = true; render(); const [roles, users, logs] = await Promise.all([fetchRoles(), fetchUsers(), fetchAuditLogs()]); state.roles = roles.data || []; state.users = users.data || []; state.logs = logs.data || []; state.loading = false; render(); }
  async function save(userId) { const role = root.querySelector(`[data-role-select="${CSS.escape(userId)}"]`)?.value; const result = await updateUserRole(userId, role); state.message = result.message || (result.success ? 'Rol güncellendi.' : 'Rol güncellenemedi.'); await load(); }
  function render() { root.innerHTML = `<section class="admin-module-page"><div class="admin-module-head"><div><p class="kicker">RBAC</p><h2>Kullanıcı Rolleri ve İzin Yönetimi</h2><small>Rol değişiklikleri audit log'a yazılır.</small></div><span class="admin-permission-badge">users.manage_roles</span></div>${state.loading ? '<p class="admin-loading">Yükleniyor...</p>' : ''}${state.message ? `<p class="admin-success">${escapeHtml(state.message)}</p>` : ''}<div class="role-table-wrap"><table class="admin-report-table"><thead><tr><th>Kullanıcı</th><th>E-posta</th><th>Mevcut Rol</th><th>Yeni Rol</th><th></th></tr></thead><tbody>${state.users.map(u => `<tr><td>${escapeHtml(u.name || u.id)}</td><td>${escapeHtml(u.email || '')}</td><td>${escapeHtml((u.roles || []).join(', '))}</td><td><select data-role-select="${escapeHtml(u.id)}">${state.roles.map(r => `<option value="${escapeHtml(r.slug)}" ${(u.roles || []).includes(r.slug) ? 'selected' : ''}>${escapeHtml(r.name)}</option>`).join('')}</select></td><td><button type="button" data-save-role="${escapeHtml(u.id)}">Kaydet</button></td></tr>`).join('')}</tbody></table></div><section><h3>Audit Log</h3><div class="audit-log-list">${state.logs.slice(0, 12).map(l => `<article><strong>${escapeHtml(l.action)}</strong><span>${escapeHtml(l.actor_user_id)} → ${escapeHtml(l.target_type)}:${escapeHtml(l.target_id)}</span><small>${escapeHtml(l.created_at)}</small></article>`).join('') || '<p class="admin-empty">Audit log yok.</p>'}</div></section></section>`; root.querySelectorAll('[data-save-role]').forEach(btn => btn.addEventListener('click', () => save(btn.dataset.saveRole))); }
  load(); return { load };
}
